name = "DoctorDocstrings"
uuid = "ad33de52-177b-401c-bbc8-ca9a9e082407"
authors = ["miguel raz <miguelraz@gmail.com> and contributors"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
TerminalMenus = "dc548174-15c3-5faf-af27-7997cfbde655"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
TypedTables = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
